### ISSUE TITLE
Project direction

### ISSUE THREAD

**Issue by Veykril** [Veykril/pagliascii#1]
Discussion regarding the projects direction and current status. This will be updated occasionally.
As there is currently no proper spec this project will try to roughly follow what asciidoctor does https://docs.asciidoctor.org/asciidoc/latest/.

Notice: As I have exams coming up currently initial progress may be slow.

**Comment by jamesmunns** [comment]
Hi Lukas,

Thanks again for volunteering to work on this! I haven't tried doing a pledge-funded open source project, so I'm pretty flexible with however we decide to go about this. Here's a couple thoughts, let me know what you think.

In terms of process, I'd probably propose the following steps, as this is roughly what we do at Ferrous Systems for our clients:

1. We've defined a super rough sketch of the [deliverables](https://gist.github.com/jamesmunns/06f70b68bde8e1394b79e936a8599718#deliverables), which have different amounts of funding set for them.
2. I think the next step would be to refine this a bit, basically just to get a "common understanding" about what "done" means, so there isn't confusion at the end of the project. I'd suggest you propose what you think is possible/reasonable/what you plan to do, and if there are no concerns, we can update the gist with those details.
3. I'd suggest you propose an update cadence (every 1/2/4/6 weeks), not necessarily for "deadlines", but just so there is a "sign of life" somewhat regularly. This helps let us know if it might make sense to find someone else to pick up the work. It would probably also be good to agree on a time limit for "no progress made", in case you get busy with other stuff. As long as you are still making progress/updates, we don't have any hard deadlines for delivery!
4. Once you think you have one of the deliverables complete, we can have a quick review to make sure everything looks good. Basically if you check the boxes we agreed on in step two, you're good to go, and I'll start bugging people to transfer funds to you.

I'm not sure if you have any preference on how you like running projects, whether you'd like to plan out/discuss all three deliverables now (and maybe revise later), or to focus on one at a time. I'll leave it up to you, but I'm always happy to chat in case you are feeling stuck!

Regarding step two above ("Acceptance Criteria"), I'd say picking some flavor/implementation of AsciiDoc that already has tests might be good for showing side by side consistency! AsciiDoctor seems to have a [bunch of tests](https://github.com/asciidoctor/asciidoctor/tree/master/test), which might help? f you're looking for suggestions, I can try and ping some more active users of AsciiDoc for help.

Two side notes that came from a [comment on the gist](https://gist.github.com/jamesmunns/06f70b68bde8e1394b79e936a8599718#gistcomment-3598515):

1. You will probably need to rename the repo because `asciidoc` is a trademark (TIL). Up to you to pick a name, or let me know if you want help coming up with one :)
2. @mojavelinux has proposed you working with the asciidoc-wg to help define/implement/collaborate on the specification of the language. I'll leave that up to you whether you are interested in that or not, but none of the current funding pledges are based on you doing or not doing that.

Lemme know what you think! I'm happy to speak publicly or privately.

**Comment by Veykril** [comment]
> I'd suggest you propose what you think is possible/reasonable/what you plan to do, and if there are no concerns, we can update the gist with those details.

I'll think about this a bit the coming days and come back with my thoughts then regarding the possible approaches, scope etc. that I think are reasonable as well as other question that might come up at the start. One thing that I can immediately ask though is that at first interest was in a rough api similarity with `pulldown_cmark`, is this still the case? I assume not given it's not listed in the gist. And I agree, as there currently is no proper spec, trying to stick to what `AsciiDoctor` currently deems reasonable specwise is probably the best choice for the time being, until the spec is finished.

> I'd suggest you propose an update cadence (every 1/2/4/6 weeks), not necessarily for "deadlines". [..]

This sounds good to me, I'd say I'll try to give updates roughly every 2 weeks, seems like a good timeframe in my eyes for now, although my upcoming exams might slow that down a bit for the first month.

> I'm not sure if you have any preference on how you like running projects, whether you'd like to plan out/discuss all three deliverables now (and maybe revise later) [..]

I think the mdbook one can be left out for now as I don't see it influencing decisions for the parser(do tell if I might be wrong about this). So I think only planning the first deliverable should be hood enough for now, with the third in mind of course since the `Format-Preserving re-serialization` part sets specific requirements the parser has to fulfill.

> Two side notes that came from a comment on the gist:

Regarding the name, if you have a good one in mind feel free to share. I'm always doing bad with these kinda names but I'll try to think of something as well 😄 

Regarding the workgroup I'll think about that whether it lies in my interest or not. 👍

**Comment by jamesmunns** [comment]
Hey!

Regarding similarity to `pulldown-cmark`, I'd say my *actual* goal is that it is easy for applications that support markdown currently to also support asciidoc. I'd say more than trying to make that a requirement, that could just be something you aim for? In particular, tools like rustdoc, zola, and mdbook are the tools I use the most with Markdown as input.

Regarding names, I had a chat with @manishearth and @mgattozi, and they suggested `pagliascii` based on [the joke](https://knowyourmeme.com/memes/but-doctor-i-am-pagliacci). I could imagine a funny clown logo :). My second place suggestion would be `iso646doc`, since ISO646 is where ASCII was standardized.

**Comment by yerke** [comment]
May I suggest `ruscii` or `rusciidoc` as alternative names?

**Comment by Veykril** [comment]
I like the `pagliascii` word/joke play the most I think so I'll go with that. Though `rusciidoc` would've been nice as well.

I renamed the repo so you can update the repo link in the gist. 👍

**Comment by mojavelinux** [comment]
Thanks @Veykril! I really appreciate you making that change. Best of luck!

**Comment by mojavelinux** [comment]
> Regarding the workgroup I'll think about that whether it lies in my interest or not. 

@Veykril My advice here is to use the Working Group (or AsciiDoc langauge project once its up to speed) to get feedback when you run into problems or need clarification. I think that will fit right into the flow of your effort here, not something that is extract. We (the AsciiDoc community) don't want you to feel like you're in isolation, and the authority on the matter of AsciiDoc is that group. So that's where I encourage you to turn for guidance (being clear that I don't speak for this grant, which is a different thing, only how AsciiDoc is represented / interpreted).

**Comment by Veykril** [comment]
@mojavelinux that sounds like a good plan, I'll keep that in mind, thanks for the info!

**Comment by Veykril** [comment]
@jamesmunns Regarding the fleshing out what "done" means in regards to the deliverable I'd say it would probably make more sense to talk that out in a voice call after all? Seems like something that works better with a conversation than messaging. I tried reaching you on twitter, until I noticed you tweeted that you are taking a break from the site(also tried you ferrous mail which didn't work out either). Let me know what you think and whether you currently have time( I don't mind if it has to wait a bit I'm still semi-stuck figuring out the proper approach I want to take for this).

**Comment by jamesmunns** [comment]
@Veykril that sounds great! Do you want to grab a time on my [calendly](https://calendly.com/bitshiftmask/) schedule? (You can ignore the podcast/recording notes and stuff, but it's probably the easiest way to schedule a Zoom call for me).

**Comment by Veykril** [comment]
Done 👍

**Comment by jamesmunns** [comment]
Hey @Veykril, I'm not sure when your exams are complete, but it might be good to chat about your "status ping" schedule, and we can probably close out this issue for now.

Let me know what you think about keeping a progress report somewhere, I'm happy to help set anything up. I think even just a `STATUS.md` in the repo with new content added periodically is totally fine.

**Comment by Veykril** [comment]
Oh I apologize @jamesmunns, I meant to get back to you as well since I realized a few days ago that we didn't specify how to do the status updates but I seem to have forgotten that. A progress report sounds good. I'm fine with just keeping a file in the repo for it(I'm open for other ideas as well though if you got some good ones). On another note, would anything else beside implementation updates go into the status updates or is that all that's going in there(might be a weird question but I figured clarifying this would be good as well)?

I'm unfortunately not quite sure when my exam period will be over(stuffs moving a bit around still thanks to covid regulations). But I've been looking into things still that aren't directly related to writing code, like where to draw inspiration from for the lexer and parser as well as API etc to get a better picture of the project(maybe this can also go into the status updates?).

**Comment by Veykril** [comment]
@jamesmunns I put up a status.adoc file now, https://github.com/Veykril/pagliascii/blob/master/STATUS.adoc

Let me know if I should record things there I am not recording yet(be it now or after some more entries in the future). I'll be able to start working on this project now finally.

**Comment by jamesmunns** [comment]
Hey, that sounds great! Sorry for not responding above. I think if you make regular status updates there, that should be perfect for folks to follow.

I think we can close this issue now, unless you'd like to keep it around for general questions!

**Comment by Veykril** [comment]
No problem!

**Comment by mojavelinux** [comment]
I wanted to chime in to let you know that the development list for the AsciiDoc Language is now active. If you have any questions about how something should be implemented in the language, please query that list and we'll make sure you get the information you need. By directing your question to that list, you can be sure that you're getting accurate advice and are on the "standards track" so to speak.

See https://www.eclipse.org/lists/asciidoc-lang-dev/ to subscribe. Hope to see you there!

**Comment by mojavelinux** [comment]
> The preprocessor will have to be a seperate pass over the document as this will simplify parsing by quite a bit. 

I've been thinking a lot about this problem lately. In order to use a parsing framework to parse the language, the only viable approach is to handle the preprocessor in a separate pass. However, as it stands now, there is a coupling between the preprocessor and the structural (i.e., element) processor*. We are going to need to tease these apart. I'm just not sure how yet. It will likely be a topic of discussion on the list.

\* Historically, AsciiDoc has not been parsed using a parsing framework. In other words, there is no formal grammar for AsciiDoc (like EBNF) that has ever been tested and used. But a key goal of the specification process is to get there.
